dataset: mimiciii
task: mortality_prediction
seed: 0
save_test: True
save_params: True

train_batch_size: 128
val_batch_size: 128
test_batch_size: 128
max_epoch: 300
early_stopping_threshold: 20
early_stopping_indicator: AUPRC
bootstrap_num: 100
logging_freq: 50
val_freq: 1

static_feats_num: 49
intervention_feats_num: 14
vital_feats_num: 3
window_size: 48
window_increment: 12

model:
  name: HIP
  mode: train
  args:
scoring_hidden_dim: 64
k_coeffs: 8
static_hidden_sizes: [32, 32]
dynamic_layers: 2
fuse_dim: 32
predictor_hidden_sizes: [32, 32]
activation: tanh
dropout: 0.1
softmax_temp: 1.0

optimizer:
  name: Adam
  args:
lr: 0.0005

scheduler:
  name: ExpLR
  args:
gamma: 0.995

criterion:
  binary_entropy:
    reduction: mean

val_metrics:
  AUPRC:
    args: None

test_metrics:
  AUROC:
    args: None
  AUPRC:
    args: None
  F1:
    args: None
  Accuracy:
    args: None

processed_data_path:
log_data_path:
