dataset: mimiciii
task: mortality_prediction
seed: 0
save_test: True
save_params: True

train_batch_size: 128
val_batch_size: 128
test_batch_size: 128
max_epoch: 300
early_stopping_threshold: 20
early_stopping_indicator: AUPRC
bootstrap_num: 100
logging_freq: 50
val_freq: 1

static_feats_num: 49
intervention_feats_num: 14
vital_feats_num: 3
window_size: 48
window_increment: 12

model:
  name: RETAIN
  mode: train
  args:
hidden_dim: 32
dropout: 0.1

optimizer:
  name: Adam
  args:
lr: 0.0005

scheduler:
  name: ExpLR
  args:
gamma: 0.995

criterion:
  binary_entropy:
    reduction: mean

val_metrics:
  AUPRC:
    args: None

test_metrics:
  AUROC:
    args: None
  AUPRC:
    args: None
  F1:
    args: None
  Accuracy:
    args: None

processed_data_path: C:\Users\ZC\Documents\GitHub\PhD_Assessment_2025\data\processed
log_data_path: C:\Users\ZC\Documents\GitHub\PhD_Assessment_2025\logs
